# Data Extraction and Initial Probing
This notebook handles the initial ingestion of the raw CSV files and performs basic checks on their structure and contents.

In [1]:
%pip install pandas numpy

import pandas as pd
import numpy as np
import os

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/shivanshupadhayay/Library/Python/3.12/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/shivanshupadhayay/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: pip3.12 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

## 1. Load Raw Datasets

In [2]:
urls = {
    'calendar': 'https://drive.google.com/uc?export=download&id=1jnbXUjOaWxb6oTQh7ZGc8hrsvRbBTZzz',
    'customers': 'https://drive.google.com/uc?export=download&id=16iirMkTGEWdqge_tNs18hkBY-hBrigcD',
    'products': 'https://drive.google.com/uc?export=download&id=1hFeWT03Cr6EImUzO-bTJ-i2d7q3sp83Z',
    'sales': 'https://drive.google.com/uc?export=download&id=1vrypPferlfcZFJTTBKExYAvLxvat6w0Z',
    'stores': 'https://drive.google.com/uc?export=download&id=1cGYO7XGxZd11lz7m8PxiRKssYgkwJGtW'
}

dataframes = {}
for table_name, url in urls.items():
    dataframes[table_name] = pd.read_csv(url)
    print(f"Loaded {table_name} from Google Drive.")

Loaded customers.csv as 'customers' table.
Loaded products.csv as 'products' table.
Loaded calendar.csv as 'calendar' table.
Loaded stores.csv as 'stores' table.
Loaded sales.csv as 'sales' table.

## 2. Basic Information (Info & Shape)

In [3]:
for name, df in dataframes.items():
    print(f"\n{'='*50}")
    print(f"TABLE: {name.upper()} (Shape: {df.shape})")
    print(f"{'='*50}")
    df.info()
    print("\n")

==================================================
TABLE: CUSTOMERS (Shape: (50000, 5))
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     50000 non-null  str
 1   age             50000 non-null  int64
 2   gender          50000 non-null  str
 3   loyalty_member  50000 non-null  int64
 4   join_date       50000 non-null  str
dtypes: int64(2), str(3)
memory usage: 1.9 MB



==================================================
TABLE: PRODUCTS (Shape: (200, 6))
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     200 non-null    str
 1   product_name   200 non-null    str
 2   brand          200 non-null    str
 3   category       200 non-null    str
 4   cocoa_percent  200 non-null    int64
 5   weight_g       200 non-null    int64
dtypes: int64(2), str(4)
memory usage: 9.5 KB



==================================================
TABLE: CALENDAR (Shape: (731, 6))
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         731 non-null    str
 1   year         731 non-null    int64
 2   month        731 non-null    int64
 3   day          731 non-null    int64
 4   week         731 non-null    int64
 5   day_of_week  731 non-null    int64
dtypes: int64(5), str(1)
memory usage: 34.4 KB



==================================================
TABLE: STORES (Shape: (100, 5))
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    100 non-null    str
 1   store_name  100 non-null    str
 2   city        100 non-null    str
 3   country     100 non-null    str
 4   store_type  100 non-null    str
dtypes: str(5)
memory usage: 4.0 KB



==================================================
TABLE: SALES (Shape: (1000000, 11))
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 11 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   order_id     1000000 non-null  str
 1   order_date   1000000 non-null  str
 2   product_id   1000000 non-null  str
 3   store_id     1000000 non-null  str
 4   customer_id  1000000 non-null  str
 5   quantity     1000000 non-null  int64
 6   unit_price   1000000 non-null  float64
 7   discount     1000000 non-null  float64
 8   revenue      1000000 non-null  float64
 9   cost         1000000 non-null  float64
 10  profit       1000000 non-null  float64
dtypes: float64(5), int64(1), str(5)
memory usage: 83.9 MB

## 3. Data Preview (Head)

In [4]:
for name, df in dataframes.items():
    print(f"\n--- First 3 rows of {name.upper()} ---")
    display(df.head(3))

--- First 3 rows of CUSTOMERS ---

  customer_id  age  gender  loyalty_member   join_date
0     C000001   40    Male               1  2025-05-21
1     C000002   47    Male               0  2021-12-26
2     C000003   58  Female               1  2022-09-13

--- First 3 rows of PRODUCTS ---

  product_id           product_name    brand category  cocoa_percent  weight_g
0      P0001    White Chocolate 80%     Mars  Truffle             80       120
1      P0002     Dark Chocolate 70%  Cadbury  Praline             70       100
2      P0003  Truffle Chocolate 70%  Hershey  Praline             70       120

--- First 3 rows of CALENDAR ---

         date  year  month  day  week  day_of_week
0  2023-01-01  2023      1    1    52            6
1  2023-01-02  2023      1    2     1            0
2  2023-01-03  2023      1    3     1            1

--- First 3 rows of STORES ---

  store_id         store_name       city country store_type
0     S001  Chocolate Store 1   New York  Canada     Retail
1     S002  Chocolate Store 2  Melbourne  Canada       Mall
2     S003  Chocolate Store 3     Berlin  France       Mall

--- First 3 rows of SALES ---

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75

## 4. Descriptive Statistics

In [5]:
for name, df in dataframes.items():
    print(f"\n--- Summary Stats for {name.upper()} ---")
    display(df.describe(include='all').T)

--- Summary Stats for CUSTOMERS ---

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,50000,50000,C000001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,50000.0,NaN,NaN,NaN,44.0261,15.328333,18.0,31.0,44.0,57.0,70.0
gender,50000,2,Male,25242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loyalty_member,50000.0,NaN,NaN,NaN,0.50208,0.500001,0.0,0.0,1.0,1.0,1.0
join_date,50000,1827,2023-09-06,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Summary Stats for PRODUCTS ---

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
product_id,200,200,P0001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_name,200,25,Dark Chocolate 50%,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
brand,200,6,Cadbury,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
category,200,5,Praline,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cocoa_percent,200.0,NaN,NaN,NaN,69.15,14.623499,50.0,50.0,70.0,80.0,90.0
weight_g,200.0,NaN,NaN,NaN,107.5,50.898954,50.0,80.0,100.0,120.0,200.0

--- Summary Stats for CALENDAR ---

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
date,731,731,2023-01-01,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,731.0,NaN,NaN,NaN,2023.500684,0.500342,2023.0,2023.0,2024.0,2024.0,2024.0
month,731.0,NaN,NaN,NaN,6.519836,3.451913,1.0,4.0,7.0,10.0,12.0
day,731.0,NaN,NaN,NaN,15.738714,8.809949,1.0,8.0,16.0,23.0,31.0
week,731.0,NaN,NaN,NaN,26.465116,15.076602,1.0,13.0,26.0,39.5,52.0
day_of_week,731.0,NaN,NaN,NaN,2.997264,2.004787,0.0,1.0,3.0,5.0,6.0

--- Summary Stats for STORES ---

           count unique                top freq
store_id     100    100               S001    1
store_name   100    100  Chocolate Store 1    1
city         100      7            Toronto   18
country      100      6             Canada   20
store_type   100      4            Airport   30

--- Summary Stats for SALES ---

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,1000000,1000000,0RD00000001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_date,1000000,731,2023-06-10,1463,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_id,1000000,202,P0021,5141,NaN,NaN,NaN,NaN,NaN,NaN,NaN
store_id,1000000,100,S013,10194,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,1000000,50000,C044952,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
quantity,1000000.0,NaN,NaN,NaN,2.999589,1.413621,1.0,2.0,3.0,4.0,5.0
unit_price,1000000.0,NaN,NaN,NaN,9.002449,3.462902,3.0,6.0,9.01,12.0,15.0
discount,1000000.0,NaN,NaN,NaN,0.056248,0.076809,0.0,0.0,0.0,0.15,0.2
revenue,1000000.0,NaN,NaN,NaN,25.486129,16.367864,2.4,12.16,21.92,35.88,75.0
cost,1000000.0,NaN,NaN,NaN,15.291554,9.972706,1.2,7.24,13.03,21.41,52.43
profit,1000000.0,NaN,NaN,NaN,10.194565,6.77876,0.73,4.78,8.6,14.17,37.43

## 5. Missing Values Check

In [6]:
for name, df in dataframes.items():
    missing = df.isnull().sum()
    if missing.sum() > 0:
        print(f"\n--- Missing Values in {name.upper()} ---")
        print(missing[missing > 0])
    else:
        print(f"{name.upper()}: No missing values detected.")

CUSTOMERS: No missing values detected.
PRODUCTS: No missing values detected.
CALENDAR: No missing values detected.
STORES: No missing values detected.
SALES: No missing values detected.